### ISSUE TITLE
Having trouble understanding documentation

### ISSUE THREAD

**Issue by Lvl50Hornist** [utopia-rise/fmod-gdextension#249]
I have almost zero background in programming, just some very basic self taught BS from ten years ago, and I am having a very hard time trying to parse how to start getting this to work.

To test things before my team started work on their current project, I made a demo Godot project and loaded in some simple banks to test and I was able to get sound to play just with an autoplay node. I was able to change parameters in the node viewer and it changed the sound as expected.

I assumed that would be enough to indicate I could figure it out, since I had taken a quick look at the documentation and it seemed pretty clear. 

Once I actually got started, I began having major issues just doing anything with the scripting inside the node. 

I copied the documentation script verbatim, aside from changing the path to the parameter to the one I was using, but nothing works at all, and the project crashes immediately.

All this to say: I don't necessarily need help with that specific problem, or have a bug or anything that I know of, but am wondering if I could get a more detailed explanation of the general setup process for this integration, because I'm having trouble understanding exactly what the nature of the integration is, which I think makes it much harder for me to troubleshoot.

Do I need to use the low level scripting or can I do basic stuff with nodes and scripting internally to them?

Do I need to use the API and whatever that entails, or is the plugin sufficient for some things?

iirc the unity and unreal integrations set up most things automatically, (I know y'all can't do that with fmod libs,) so what do I need to do to emulate that? the documentation says how to compile it, but is a bit vague about it. 

do I even need to set that up while testing the project, or just when compiling?

In the example project, what does each piece of it do, precisely? Some detailed comments in the example project could help this significantly, as the more I learn about Godot, the more confused I become with the fmod integration, and I assume I have a basic misunderstanding somewhere.

I apologize if this is outside the scope of what you all are able to help with. I just am usually able to figure stuff out by digging through the documentation, but I'm super stumped right now. I appreciate any and all help you can give, thanks so much, regardless.

**Comment by Lvl50Hornist** [comment]
Also apologies if this is better suited to a different section here. I am pretty new to git, so sorry! happy to move it if that's the case.

**Comment by CedNaru** [comment]
Hi,
First sorry for the confusing documentation, we want to improve it, but we are so taken by different projects that it's hard to find the time to redo it properly.
Let's start from the beginning. You don't need to compile anything, the instructions for it are just meant for people who want to add their own changes to the C++ code and make their custom version.
You only need to download the addons.zip and drop its content into the addons/ directory of your project. this archive contains all the libraries, both for Godot and Fmod. 
Then the integration itself is split into 2 main parts: the high level ones that provide Nodes you can directly use in your scene, and the low level ones that can directly manipulate the same object the Nodes are using behind the hood. See the nodes as simply wrapping the low level API.

Nodes are designed in a way that 80% of your basic needs are covered by just setting parameters on them. You can then add scripts to them and write some game logic in it. That part is made to be closer to Godot. You don't need the low level API for it.
Now the low level API is quite straightforward, most of it is simply the official FMOD C++ API made available to GDScript as a Godot Server. The documentation is extremely minimal about it because most of it already exists in the official FMOD documentation: https://www.fmod.com/docs/2.02/api/studio-api.html

It's not 1 to 1, we slightly adapted it to be more Godot like, but you can read it and get a pretty close idea of how to use our own API. Everything related to `Common` and `System` in the official API is going to become a method of `FmodServer` in this integration. The rest is pretty much unchanged. We didn't reimplement 100% of the API so some parts are still missing. 

If you don't have a programming background, I would advise against using the low level API You should focus on using nodes only for now, you can add scripts to them for better control, just like you would add a script to a Node2D and write a basic logic to move it for example, but all of that doesn't require to use the low level API. The node API itself offers plenty of options (Of still it's still far from perfect and more methods could be added if people ask for it).
Then if you really need to get into more precise behaviour, all nodes provide a method to obtains the low level object they wrap. For example, FmodEmitter has the `get_event()`, that will return the `FmodEvent` low level object on which you can use the FMOD API directly.

Regarding the demos in the project, we have 3 of them. Low level 2D, High level 2D and High level 3D. Low level are implemented using the API only, and high level is implemented using the Nodes only. The two 2D demos are the same, but implemented differently, the 3D demo is there because we needed to debug some 3D maths so it was added more recently. You can mostly focus on the 2D demos to understand the differents between those 2 ways of using the integration.

**Comment by Lvl50Hornist** [comment]
That is EXTREMELY helpful, thank you so much. I appreciate the time and effort!
