### ISSUE TITLE
Can't change the event of an FMODEventEmitter

### ISSUE THREAD

**Issue by YuriPrickles** [utopia-rise/fmod-gdextension#256]
so my eventemitter (which is autoloaded) is set to a certain song by default, and when i load a scene i always make sure to change the event_name of the eventemitter and the do play(). for soem reason it still plays the default event.

is this intended? attached below is an example of the code i wrote to change the event. let me know if you need anything more
![{E0813C27-BE37-4A77-AE56-7868162762DE}](https://github.com/user-attachments/assets/77e14824-1615-4536-8624-ce271f613bce)

**Comment by CedNaru** [comment]
Is your Node set with autoplay ?
If yes, then here's the explanation. 
Right now the behaviour (which is not the best one, I admit) is that autoplay will automatically load your default song when your Node calls _ready(), because of script inheritance and such, our code for `_ready` get called before yours script code. Autoplay makes your default song instanced first. The issue with `play()` is that it's basically a no-op if a song is already playing. We forgot to make it check if the currently set event is different from one playing.

If no, I need to go back, check the code to be sure what's the sequence of event.

**Comment by LawnmowerKing** [comment]
> Is your Node set with autoplay ? If yes, then here's the explanation. Right now the behaviour (which is not the best one, I admit) is that autoplay will automatically load your default song when your Node calls _ready(), because of script inheritance and such, our code for `_ready` get called before yours script code. Autoplay makes your default song instanced first. The issue with `play()` is that it's basically a no-op if a song is already playing. We forgot to make it check if the currently set event is different from one playing.
> 
> If no, I need to go back, check the code to be sure what's the sequence of event.

nope, it doesnt have autoplay.

**Comment by YuriPrickles** [comment]
i even tried stopping it, and then setting the event name, and finally playing it, but that doesnt seem to work as well

**Comment by YuriPrickles** [comment]
my current solution for this is just to put every event into 1 fmod event

**Comment by CedNaru** [comment]
Should be solved by #268 
Will be in the next release.
